name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            libcurl4-openssl-dev \
            libgl1-mesa-dev

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --config Release
